apiVersion: v1
kind: Service
metadata:
  name: back-service
  labels:
    {{- include "demochart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.servicetype }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.backend.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "demochart.selectorLabels" . | nindent 4 }}
