apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    component: web-f
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      component: web-f
  template:
    metadata:
      labels:
        component: web-f
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "demochart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.frontend.image.repository }}"
          
          ports:
            - name: http
              containerPort: {{ .Values.frontend.targetPort  }}
              protocol: TCP

          volumeMounts:
          - name: my-config-volume
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
      volumes:
        - name: my-config-volume
          configMap:
            name: my-config     

