apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
   component: web-f
spec:
  type: {{ .Values.frontend.servicetype }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.frontend.targetPort }}
      protocol: TCP
  selector:
    component: web-f
